Add how to send and receive context
scalar-labs/scalardl pull request #47
Opened 2023-04-28 09:13 UTC by feeblefakie

This PR adds some descriptions about how to send and receive context in ScalarDL Contracts and Functions.

2023-05-01 05:26 UTC, supl approved these changes
LGTM.
Thank you!

2023-05-01 09:04 UTC, josh-wong requested changes
I made a few suggestions. PTAL!

2023-05-01 09:04 UTC, josh-wong commented on docs/how-to-write-function.md
> +Note that the return value can be null if nothing has been set by Contracts and the return value type `T` will be decided based on a base Function class that you use.
Revised to reduce passive voice.

```suggestion
Note that the return value can be null if Contracts has nothing set and the base Function class that you use will decide the return value type `T`.
```

2023-05-01 09:04 UTC, josh-wong commented on docs/how-to-write-function.md
> +
Revised to specify link name.

```suggestion
For details on how to send information to Functions from Contracts, see [Send information to Functions](./how-to-write-contract.md#send-information-to-functions).
```

2023-05-01 09:16 UTC, feeblefakie commented
@josh-wong Thanks! Applied all the suggestions.

2023-05-01 09:18 UTC, josh-wong approved these changes
LGTM!🚀

2023-05-02 02:00 UTC, jnmt approved these changes
LGTM! Thank you! I don't think this is the scope of this PR, but it would be nice if we could add a use case or a concrete example that uses this feature so that users get hints about when they should use this in their development.

2023-05-02 03:04 UTC, reddikih approved these changes
LGTM! Thank you.

> LGTM! Thank you! I don't think this is the scope of this PR, but it would be nice if we could add a use case or a concrete example that uses this feature so that users get hints about when they should use this in their development.

I would like to make a sample code and a blog post to show the usage of this feature.

2023-05-02 06:23 UTC, merged