Add generic contracts for object authenticity management
scalar-labs/scalardl pull request #62
Opened 2024-07-23 05:46 UTC by jnmt

## Description

> Provide a brief description about **why** this PR is necessary. Be sure to provide context.

## Related issues and/or PRs

> If this PR addresses or references any issues and/or other PRs, list them here.

## Changes made

> Outline the specific changes made in this pull request. Include relevant details, such as added features, bug fixes, code refactoring, or improvements.

## Checklist

> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the checkboxes after you have read and understood each item.

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation to reflect the changes.
- [ ] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [ ] Tests (unit, integration, etc.) have been added for the changes.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

> Provide any additional information or notes that may be relevant to the reviewers or stakeholders.

## Release notes

> Provide release note text for this PR based on the guidelines at [Guidelines for Writing Release Notes](https://developers.scalar-labs.com/docs/style-guide/release-notes/).
> 
> For example:
> 
> Added validation for the Consensus Commit mutation operation.

2024-07-23 13:05 UTC, josh-wong requested changes
I've added some minor suggestions. PTAL!

2024-07-23 13:05 UTC, josh-wong commented on generic-contracts-and-functions/src/main/java/com/scalar/dl/client/Constants.java
> +      "The object ID is not specified in the arguments or invalid.";
```suggestion
      "The object ID is not specified in the arguments or is invalid.";
```

2024-07-23 13:05 UTC, josh-wong commented on generic-contracts-and-functions/src/main/java/com/scalar/dl/client/Constants.java
> +      "The hash value is not specified in the arguments or invalid.";
```suggestion
      "The hash value is not specified in the arguments or is invalid.";
```

2024-07-23 13:05 UTC, josh-wong commented on generic-contracts-and-functions/src/main/java/com/scalar/dl/client/Constants.java
> +      "The specified format of the properties is not valid.";
For consistency with the other messages above, how about if we change this to `invalid`?

```suggestion
      "The specified format of the properties is invalid.";
```

2024-07-23 13:05 UTC, josh-wong commented on generic-contracts-and-functions/src/main/java/com/scalar/dl/client/Constants.java
> +      "The specified format of the hash values is not valid.";
For consistency with the other messages above, how about if we change this to `invalid`?

```suggestion
      "The specified format of the hash values is invalid.";
```

2024-07-24 01:01 UTC, supl approved these changes
LGTM!
Thank you.
I think it's nice to have them.

2024-07-24 05:44 UTC, jnmt commented
As discussed with Hiro, we decided to include generic contracts and functions in the scalar-labs/scalar main repository so that we can easily run e2e tests with generic contracts. So, I will close this and re-create a PR in it.

@josh-wong @supl Thank you for the review and suggestions. I will apply them in the re-created PR, so PTAL it again. Sorry for the inconvenience.

2024-07-24 05:44 UTC, closed without merging